name: build kernel
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'
      # - '*'
  workflow_dispatch: 
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false
      march:
        type: string
        description: |
          Override target architecture, Use special value "0" to clear the default
        required: false
        default: ""
      opt:
        type: string
        description: 'Override optimization flag'
        required: false
        default: ""
      build_docs:
        type: boolean
        description: 'Build Documentation'
        required: false
        default: false
permissions:
  contents: write
jobs:
  build_and_release:
    timeout-minutes: 360
    runs-on: ubuntu-latest
    strategy:
      # Disable fail-fast, as the ssh debugging step may fail during the build process.
      fail-fast: false
    container:
      image: archlinux:base-devel 
      options: --privileged
      volumes:
        - /:/host
    steps:
      - name: Prepare packages
        run: |
          pacman -Syu --noconfirm --needed ccache git rsync
          echo 'root ALL=(ALL:ALL) NOPASSWD: ALL' >> /etc/sudoers
          
      - name: ssh debug
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
        with:
          detached: true

      - name: Prepare runner user
        run: |
          useradd -m runner
          echo 'runner ALL=(ALL:ALL) NOPASSWD: ALL' >> /etc/sudoers

      - uses: actions/checkout@v3

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with: 
          key: ${{ github.run_id }}
          max-size: 1024M

      # A full kernel build requires at least 28GB of free space.
      - name: Freeup space
        run: |
          mkdir /empty -p
          _files=(
            /usr/local/lib/android
            /usr/local/.ghcup
            /usr/local/share/powershell
            /usr/local/share/chromium
            /usr/local/share/vcpkg
            /usr/share/dotnet
            /usr/share/swift
            /opt/hostedtoolcache/CodeQL
          )
          for f in ${_files[@]}; do 
            rsync -r --delete /empty/ "/host/$f"
          done

      - name: Prepare source
        run: |
          chown -R runner:runner .
          sudo -u runner cp dist/options-znver2.conf options.conf
          sudo -u runner makepkg --nobuild --holdver --noextract -s --noconfirm

      - name: Apply ovrrides (-march)
        if: inputs.march != ''
        run: |
          if [[ "${{inputs.march}}" == "0" ]]; then
            echo "_march=" | tee -a options.conf
          else
            echo "_march=${{inputs.march}}" | tee -a options.conf
          fi

      - name: Apply ovrrides (-O)
        if: inputs.opt != ''
        run: |
          echo "_optimization=${{inputs.opt}}" | tee -a options.conf
        
      - name: Apply overrides (build_docs)
        run: |
          if [[ "${{inputs.build_docs}}" == "true" ]]; then
            echo "_build_docs=1" | tee -a options.conf
          else
            echo "_build_docs=0" | tee -a options.conf
          fi

      - name: Build kernel
        run: |
          sudo -u runner makepkg
      
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          path: '*.pkg.tar.zst'
        
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: '*.pkg.tar.zst'
