name: build linux kernel
# This workflow produces the artifact: "package_linux".
on:
  workflow_call:
    inputs:
      march:
        type: string
        description: target micro architecure, 
        default: generic
      pkgver:
        type: string
        description: linux release version (if blank, use value from PKGBUILD)
        required: false
      pkgrel:
        type: string
        description: reversion (if blank, use value from PKGBUILD)
        required: false
      make_jobs:
        type: number
        description: number of parallel make jobs
        default: 3 
      artifact:
        type: string
        description: name of the kernel package artifact
        default: liunx-clang
      debug:
        type: boolean
        description: run in debug mode
        default: false

jobs:
  build_kernel:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    container:
      image: archlinux:base-devel
      options: --privileged
      volumes:
        - /:/host
    steps:
      - name: Prepare
        run: |
          echo "::group::Build Configuration"
          echo "\
          Target Microarchitecture  : ${{inputs.march}}
          version                   : ${{inputs.pkgver}}
          Package Reversion         : ${{inputs.pkgrel}}
          Parallel make Jobs        : ${{inputs.make_jobs}}
          Aritifact Name            : ${{inputs.artifact}}
          Workflow debug            : ${{env.debug}}"
          echo "::endgroup::"