name: build linux kernel

on:
  workflow_call:
    inputs:
      target:
        type: string
        description: "target linux-clang kernel release (if blank, use artifact:package_linux)"
        required: false
      artifact:
        type: string
        description: name of the kernel package artifact
        default: extramodules

          
jobs:
  build_kernel:
    runs-on: ubuntu-latest
    steps:
      - name: debug output
        run: |
          echo "\
          input.target: ${{inputs.target}}
          input.artifact: ${{inputs.artifact}}
          "