name: build linux kernel
# This workflow produces the artifact: "package_linux".
on:
  workflow_call:
    inputs:
      march:
        type: string
        description: target micro architecure, 
        required: false
        default: generic
      pkgver:
        type: string
        description: linux release version (if blank, use value from PKGBUILD)
        required: false
      pkgrel:
        type: string
        description: reversion (if blank, use value from PKGBUILD)
        required: false
      make_jobs:
        type: number
        description: number of parallel make jobs
        required: false
        default: 3 
      artifact:
        type: string
        description: name of the kernel package artifact
        required: false
        default: liunx-clang
    
jobs:
  build_kernel:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    container:
      image: archlinux:base-devel
      options: --privileged
      volumes:
        - /:/host
    steps:
      - name: Prepare
        run: |
          echo "::group::Build Configuration"
          echo "\
          inputs.march: ${{inputs.march}}
          inputs.pkgver: ${{inputs.pkgver}}
          inputs.pkgrel: ${{inputs.pkgrel}}
          inputs.make_jobs: ${{inputs.make_jobs}}
          inputs.artifact: ${{inputs.artifact}}
          inputs.debug: ${{inputs.debug}}"
          echo "::endgroup::"