name: Build extra modules

on:
  workflow_dispatch:
    inputs:
      linux_cache_key:
        type: string
        description: Key used to restore linux-clang package cache
        default: linux-clang-pkg
      artifact:
        type: string
        description: name of the built package artifact
        default: extramodules
      debug:
        type: boolean
        description: run in debug mode
        default: false
      mock:
        type: boolean
        description: run in mock mode
        default: false
  workflow_call:
    inputs:
      linux_cache_key:
        type: string
        description: Key used to restore linux-clang package cache
        default: linux-clang-pkg
      artifact:
        type: string
        description: name of the built package artifact
        default: extramodules
      debug:
        type: boolean
        description: run in debug mode
        default: false
      mock:
        type: boolean
        description: run in mock mode
        default: false

permissions:
  contents: write
  actions: write

jobs:
  build_extra_modules:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
      - name: Prepare
        run: |
          echo "::group::Build Configuration"
          echo "\
          Aritifact Name            : ${{inputs.artifact}}
          Workflow debug            : ${{inputs.debug}}
          Mock mode                 : ${{inputs.mock}}"
          echo "::endgroup::"

          echo "::group::Install essential packages"
          packages=(
            ccache
            git
            rsync
            clang
            llvm
            lld
          )
          [[ -n "${{env.ACT}}" ]] && packages+=(nodejs)
          if [[ "${{inputs.debug}}" == true ]]; then
            packages+=(
              neovim
              htop
              dust
              bash-completion
              tmate
            )
            ln -sf /usr/bin/nvim /bin/vi
          fi
          pacman -Syu --noconfirm --needed "${packages[@]}"
          echo "::endgroup::"

          echo "::group::Prepare builder user"
          useradd -m builder
          echo 'builder ALL=(ALL:ALL) NOPASSWD: ALL' | tee /etc/sudoers.d/builder
          echo "::endgroup::"

      - name: Debug workflow with ssh
        uses: mxschmitt/action-tmate@v3
        if: ${{ !env.ACT && inputs.debug }}
        with:
          detached: true
      
      - uses: actions/checkout@v3
      
      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          append-timestamp: false
          key: linux-extra
          max-size: 64M
      
      - name: Load kernel package from cache
        uses: actions/cache/restore@v3
        with:
          key: ${{inputs.linux_cache_key}}
          path: '*.pkg.tar.zst'
      
      - name: Prepare source and build environment
        run: |
          echo "::group::Configure ccache"
          su -c 'mkdir -p ~/.config/ccache' builder
          install -v -Dm644 ~/.config/ccache/ccache.conf ~builder/.config/ccache
          echo "::endgroup::"

          echo "::group::Install nvidia-dkms"
          pacman -S --noconfirm nvidia-dkms
          echo "::endgroup::"

          echo "::group::Remove bogus alpm hooks"
          rm -vf /usr/share/libalpm/hooks/*dkms*.hook
          rm -vf /usr/share/libalpm/hooks/*mkinitcpio*.hook
          echo "::endgroup::"

          if [[ "${{inputs.mock }}" != true ]]; then
            echo "::group::Install linux-clang packages"
            pacman --noconfirm -U *.pkg.tar.zst
            echo "::endgroup::"
          fi
          
          echo "::group::Fix permissions"
          chown -Rv builder:builder .
          chown -Rv builder:builder /var/lib/dkms
          echo "::endgroup::"
      
      - name: Build extra module
        run: |
          cd extra/nvidia
          if [[ "${{inputs.mock }}" != true ]]; then
            su -c "makepkg --noconfirm -fs" builder
          else
            echo "::group::Mock Build"
            tar --zstd -cf extra.pkg.tar.zst -T /dev/null
            echo "::endgroup::"
          fi
        
      - name: Post build
        run: |
          echo "::group::Remove old ccache"
          if [[ -z "${{env.ACT}}" ]]; then
            curl -H "Accept: application/vnd.github.v3+json" -H "Authorization: token $GITHUB_TOKEN" -X DELETE "$GITHUB_API_URL/repos/${{ github.repository }}/actions/caches?key=$CACHE_KEY"
          fi
          echo "::endgroup::"

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CACHE_KEY: ccache-linux-extra-

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          retention-days: 7
          name: ${{inputs.artifact}}
          path: 'extra/nvidia/*.pkg.tar.zst'
