name: caller
on: push

jobs:
  call_workflow:
    uses: ./.github/workflows/callee.yml
  # download_artifact:
  #   runs-on: ubuntu-latest
  #   needs: call_workflow
  #   steps:
  #     - uses: actions/download-artifact@v3
  #       with:
  #         name: file
  #     - run: |
  #         ls -R
  #         cat file