name: create release
# This workflow produces the artifact: "package_linux".
on:
  workflow_call:
    inputs:
      artifact_linux:
        type: string
        description: name of linux kernel package artifact
        required: false
        default: linux-clang
      artifact_extra:
        type: string
        description: name of extra modules package artifact
        required: false
        default: extramodules
      release_linux:
        type: boolean
        description: if true, release the linux kernel package
        required: false
        default: true
      release_extra:
        type: boolean
        description: if true, release the extra modules package
        required: false
        default: true
    
jobs:
  release_packages:
    name: Release packages to github
    runs-on: ubuntu-latest
    steps:
      - name: Download linux kernel artifact
        uses: actions/download-artifact@v3
        if: ${{inputs.release_linux}}
        with:
          name: ${{inputs.artifact_linux}}
      - name: Download extra modules artifact
        uses: actions/download-artifact@v3
        if: ${{inputs.release_extra}}
        with:
          name: ${{inputs.artifact_extra}}
      - name: Create release
        run: echo Mock release
        # uses: softprops/action-gh-release@v1
        # with:
        #   files: '*.pkg.tar.zst'

