name: create release
# This workflow produces the artifact: "package_linux".
on:
  workflow_call:
    inputs:
      artifact_linux:
        type: string
        description: name of linux kernel package artifact
        default: linux-clang
      artifact_extra:
        type: string
        description: name of extra modules package artifact
        default: extramodules
      release_linux:
        type: boolean
        description: if true, release the linux kernel package
        default: true
      release_extra:
        type: boolean
        description: if true, release the extra modules package
        default: true
      mock:
        type: boolean
        description: mock mode
        default: false
    
jobs:
  release_packages:
    name: Release packages to github
    runs-on: ubuntu-latest
    steps:
      - name: Download linux kernel artifact
        uses: actions/download-artifact@v3
        if: ${{inputs.release_linux}}
        with:
          name: ${{inputs.artifact_linux}}
      - name: Download extra modules artifact
        uses: actions/download-artifact@v3
        if: ${{inputs.release_extra}}
        with:
          name: ${{inputs.artifact_extra}}
      - name: Generate release tag
        id: tagging
        run: |
          if [[ "${{startsWith(github.ref, 'refs/tags')}}" == true ]]; then
            tag="$GITHUB_REF_NAME"
          elif [[ "${{inputs.release_linux}}" == true ]]; then
            tag="$(echo linux*headers*pkg.tar.zst "$(date +%s)" | sed 's/linux.*headers-//; s/-x86_64.pkg.tar.zst//;')"
          else
            tag="$(echo *pkg.tar.zst "$(date +%s)" | sed 's/-x86_64.pkg.tar.zst//')"
          fi
          echo "tag=$tag" >> "${GITHUB_OUTPUT}"
      - name: Create release
        if: ${{!inputs.mock}}
        uses: softprops/action-gh-release@v1
        with:
          files: '*.pkg.tar.zst'
          tag_name: ${{steps.tagging.outputs.tag}}
